/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_2do;

import java.io.Reader;
import java.io.StringReader;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import java_cup.runtime.ComplexSymbolFactory;

/**
 *
 * @author hector
 */
public class Interfaz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    private ListaVariables variables;
    private Nodo instrucciones;
    private String salida;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("/*calculo de 0 + 1 + 2 + ... + n - 2 + n - 1 + n,\npara un entero n*/\nn = 5\nb = 1\ni = 0\nwhile b < n + 1\n    i = i + b\n    b = b + 1\nend\nputs concat(\"sum( n = \", n, \" ) = \", i)\n\nputs \"PRUEBA DO-WHILE\"\nx = 0\ndo{\n puts x\n x = x + 1\n}while x < 3\nend\n\nputs \"PRUEBA FOR\"\nfor (j = 1 j < 11 j = j + 1)\n    puts j\nend\n\nputs \"PRUEBA SWITCH\"\nw = 2\n\nswitch (w){\n    case 1:\n        puts \"uno\"\n    case 2:\n        puts \"dos\"\n    end\n    default:\n        puts \"otro\"\n}\nend");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("Compilar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Codigo de entrada");

        jLabel2.setText("Codigo de salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(361, 361, 361))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            Reader reader = new StringReader(jTextArea1.getText());
            AnalisisLexico scanner = new AnalisisLexico(reader);
            ComplexSymbolFactory sf = new ComplexSymbolFactory();
            scanner.setSymbolFactory(sf);
            AnalisisSintactico parser = new AnalisisSintactico(scanner, sf);
            parser.parse();
            variables = new ListaVariables();
            salida = "";
            instrucciones = parser.instrucciones;
            ejecutar(instrucciones);
            jTextArea2.setText(salida);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    private void ejecutar(Nodo instrucciones) throws Exception {
        int i = 0;
        Nodo instruccion;

        while (i < instrucciones.hijos.size()) {
            instruccion = instrucciones.hijos.get(i);

            //System.out.println("Tipo instruccion: " + instruccion.valor);
            //System.out.println("[" + instruccion.valor + "]");
            //System.out.println("Variables actuales: " + variables.var.keySet());
            if (instruccion.valor.equals("asignacion")) {
                String id = instruccion.hijos.get(0).hijos.get(0).valor;
                Object val = evaluarExpresion(instruccion.hijos.get(1));
                Variable var = new Variable();
                var.nombre = id;
                var.valor = val;
                variables.agregar(var);
            } else if (instruccion.valor.equals("if")) {
                if ((Boolean) evaluarExpresion(instruccion.hijos.get(0))) {
                    ejecutar(instruccion.hijos.get(1));
                } else {
                    if (instruccion.hijos.size() == 3) {
                        ejecutar(instruccion.hijos.get(2));
                    }
                }
            } else if (instruccion.valor.equals("while")) {
                while ((Boolean) evaluarExpresion(instruccion.hijos.get(0))) {
                    ejecutar(instruccion.hijos.get(1));
                }
            } else if (instruccion.valor.equals("dowhile")) {
                do {
                    ejecutar(instruccion.hijos.get(0));
                } while ((Boolean) evaluarExpresion(instruccion.hijos.get(1)));
            } else if (instruccion.valor.equals("for")) {
                //System.out.println("Ejecutando FOR");
                ejecutar(instruccion.hijos.get(0));

                Object condicion;

                //System.out.println("Inicializacion hecha");
                while (true) {
                    condicion = evaluarExpresion(instruccion.hijos.get(1));

                    if (!(Boolean) condicion) {
                        break;
                    }

                    ejecutar(instruccion.hijos.get(3));
                    ejecutar(instruccion.hijos.get(2));
                }

            } else if (instruccion.valor.equals("switch")) {

                Object valorSwitch = evaluarExpresion(instruccion.hijos.get(0));
                Nodo listaCasos = instruccion.hijos.get(1);

                boolean ejecutar = false;

                for (Nodo caso : listaCasos.hijos) {
                    if (caso.valor.equals("case")) {
                        Object valorCase = evaluarExpresion(caso.hijos.get(0));

                        if (valorSwitch.equals(valorCase)) {
                            ejecutar(caso.hijos.get(1));
                            ejecutar = true;
                            break;
                        }
                    } else if (caso.valor.equals("default")) {
                        if (!ejecutar) {
                            ejecutar(caso.hijos.get(0));
                        }
                    }
                }

            } else if (instruccion.valor.equals("puts")) {
                salida += evaluarExpresion(instruccion.hijos.get(0)) + "\n";
            }

            i++;
        }
    }

    private Object evaluarExpresion(Nodo nodo) throws Exception {
        Nodo aux = nodo.hijos.get(0);

        //System.out.println("Nodo tipo: " + nodo.valor);
        switch (nodo.valor) {
            case "valor":
                if (aux.valor.equals("entero")) {
                    return Integer.valueOf(aux.hijos.get(0).valor);
                } else {
                    return aux.hijos.get(0).valor;
                }

            case "variable":
                Variable var = variables.buscar(aux.valor);

                //System.out.println("Buscando variable: " + aux.valor);
                if (var == null) {
                    throw new Exception("No se ha declarado la variable");
                } else {
                    return var.valor;
                }

            case "concatenar":
                String t = "";
                for (int i = 0; i < aux.hijos.size(); i++) {
                    t += String.valueOf(evaluarExpresion(aux.hijos.get(i)));
                }
                return t;

            case "and": {
                Boolean primera = (Boolean) evaluarExpresion(nodo.hijos.get(0));
                Boolean segunda = (Boolean) evaluarExpresion(nodo.hijos.get(1));
                return primera == true && segunda == true;
            }

            case "or": {
                Boolean primera = (Boolean) evaluarExpresion(nodo.hijos.get(0));
                Boolean segunda = (Boolean) evaluarExpresion(nodo.hijos.get(1));
                return primera == true || segunda == true;
            }

            case "not":
                return !(Boolean) evaluarExpresion(nodo.hijos.get(0));

            case "==": {
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));

                if (primera instanceof Integer) {
                    return Objects.equals((Integer) primera, (Integer) segunda);
                } else if (primera instanceof String) {
                    return ((String) primera).equals((String) segunda);
                } else if (primera instanceof Boolean) {
                    return Objects.equals((Boolean) primera, (Boolean) segunda);
                } else {
                    throw new Exception("No se reconoce el nodo, ==");
                }
            }
            
            case "!=":{
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));
                
                if (primera instanceof Integer) {
                    return !Objects.equals((Integer) primera, (Integer) segunda);
                } else if (primera instanceof String){
                    return !((String) primera).equals((String) segunda);                    
                } else if (primera instanceof Boolean){
                    return !Objects.equals((Boolean) primera, (Boolean) segunda);
                } else {
                    throw new Exception("No se reconoce el nodo, !=");                    
                }
                
            }

            case "<": {
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));

                if (primera instanceof Integer) {
                    return (Integer) primera < (Integer) segunda;
                } else {
                    throw new Exception("No se reconoce el nodo, <");
                }
            }
            
            case "<=": {
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));
                
                if (primera instanceof Integer) {
                    return (Integer) primera <= (Integer) segunda;
                } else {
                    throw  new Exception("No se reconoce el nodo, <=");
                }                
            }

            case ">": {
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));

                if (primera instanceof Integer) {
                    return (Integer) primera > (Integer) segunda;
                } else {
                    throw new Exception("No se reconoce el nodo, >");
                }
            }
            
            case ">=": {
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));

                if (primera instanceof Integer) {
                    return (Integer) primera >= (Integer) segunda;
                } else {
                    throw new Exception("No se reconoce el nodo, >=");
                }
            }

            case "*": {
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));

                if (primera instanceof Integer) {
                    return (Integer) primera * (Integer) segunda;
                } else {
                    throw new Exception("No se reconoce el nodo, *");
                }
            }

            case "/": {
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));

                if (primera instanceof Integer) {
                    return (Integer) primera / (Integer) segunda;
                } else {
                    throw new Exception("No se reconoce el nodo, /");
                }
            }

            case "+": {
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));

                if (primera instanceof Integer) {
                    return (Integer) primera + (Integer) segunda;
                } else {
                    throw new Exception("No se reconoce el nodo, +");
                }
            }

            case "-": {
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));

                if (primera instanceof Integer) {
                    return (Integer) primera - (Integer) segunda;
                } else {
                    throw new Exception("No se reconoce el nodo, -");
                }
            }
            
            case "%":{
                Object primera = evaluarExpresion(nodo.hijos.get(0));
                Object segunda = evaluarExpresion(nodo.hijos.get(1));
                
                if (primera instanceof Integer){
                    return (Integer) primera % (Integer) segunda;
                } else {
                    throw new Exception("No se reconoce el nodo, %");
                }                
            }

            default:
                throw new Exception("No se reconoce el nodo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
