
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package project_2do;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int CONCAT = 15;
  public static final int DOS_PUNTO = 33;
  public static final int LLAVE_ABIERTO = 4;
  public static final int ENTERO = 34;
  public static final int CASE = 14;
  public static final int ASTERISCO = 28;
  public static final int PARENTESIS_ABIERTO = 2;
  public static final int FOR = 10;
  public static final int NOT = 19;
  public static final int MENORIGUAL = 26;
  public static final int AND = 18;
  public static final int IGUAL = 21;
  public static final int OR = 17;
  public static final int IF = 6;
  public static final int ID = 36;
  public static final int PUNTO_COMA = 32;
  public static final int IGUAL_IGUAL = 20;
  public static final int MAYORIGUAL = 25;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int CADENA = 35;
  public static final int MENOS = 30;
  public static final int MENOR = 22;
  public static final int SWITCH = 12;
  public static final int MAYOR = 23;
  public static final int DISTINTODE = 24;
  public static final int PUTS = 16;
  public static final int ELSE = 7;
  public static final int LLAVE_CERRADO = 5;
  public static final int WHILE = 9;
  public static final int DEFAULT = 13;
  public static final int END = 8;
  public static final int PARENTESIS_CERRADO = 3;
  public static final int DIVISION = 29;
  public static final int DO = 11;
  public static final int MAS = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "LLAVE_ABIERTO",
  "LLAVE_CERRADO",
  "IF",
  "ELSE",
  "END",
  "WHILE",
  "FOR",
  "DO",
  "SWITCH",
  "DEFAULT",
  "CASE",
  "CONCAT",
  "PUTS",
  "OR",
  "AND",
  "NOT",
  "IGUAL_IGUAL",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "DISTINTODE",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MAS",
  "ASTERISCO",
  "DIVISION",
  "MENOS",
  "COMA",
  "PUNTO_COMA",
  "DOS_PUNTO",
  "ENTERO",
  "CADENA",
  "ID"
  };
}

